config:
  client_advertise: "nats://nats.default.svc.cluster.local:4222"
  cluster:
    enabled: true
    replicas: 3
  jetstream:
    enabled: true
    fileStore:
      pvc:
        size: 10Gi
  leafnodes:
    enabled: true
  gateway:
    enabled: true
    merge:
      name: "nats-eks"
      advertise: "k8s-default-natseks-1e51447358-beb8437f6bba706c.elb.us-east-1.amazonaws.com"
      authorization:
        user: natsgate
        password: NATSC!u5t3rGa73way
      gateways: 
      - name: "nats-eks"
        urls:
          - nats://natsgate:NATSC!u5t3rGa73way@k8s-default-natseks-1e51447358-beb8437f6bba706c.elb.us-east-1.amazonaws.com:7222
      - name: "nats-azure"
        urls:
          - nats://natsgate:NATSC!u5t3rGa73way@13.88.174.4:7222
  merge:
    accounts:
      SYS:
        users:
          - user: sys
            pass: sysuser
      teamA:
        jetstream: enabled
        users:
          - user: natsedge
            pass: NATSeDg3Us3r!
          - user: natseast
            pass: NATSC!u5t3r3@st
          - user: natswest
            pass: NATSC!u5t3rW3st
      teamB:
        jetstream: enabled
        users:
          - user: natsAdd
            pass: NATSAdd!d3r
    system_account: SYS

podTemplate:
  topologySpreadConstraints:
    kubernetes.io/hostname:
      maxSkew: 1
      whenUnsatisfiable: DoNotSchedule

service:
  ports:
    gateway:
      enabled: true
  merge:
    metadata:
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-type: external
        service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
        service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    spec:
      type: LoadBalancer
      publishNotReadyAddresses: true
      ports:
        - name: nats
          port: 4222
          targetPort: 4222
        - name: gateway
          port: 7222
          targetPort: 7222


