config:
  client_advertise: "nats://nats-east.default.svc.cluster.local:4222"
  cluster:
    enabled: true
    replicas: 3
  jetstream:
    enabled: true
    fileStore:
      pvc:
        size: 10Gi
  leafnodes:
    enabled: true
  gateway:
    # NOTE: the gateway name must match the Helm release name
    name: "nats-east"
    enabled: true
    merge:
      advertise: "k8s-default-natseast-7a73a92769-7e2f030540a4d622.elb.us-east-1.amazonaws.com:7222"
      authorization:
        user: natsgate
        password: NATSC!u5t3rGa73way
      # for this demo, I used the cloud provider's load balancer servicer.
      # that means I had to wait for the load balancer to be created before I knew
      # what the external IP address was. until then, the following two lines were
      # commented out. once the load balancer was created, I uncommented them
      # and updated the values entries with the correct endpoints.
      gateways: 
      - name: "nats-east"
        urls:
          - nats://natsgate:NATSC!u5t3rGa73way@k8s-default-natseast-7a73a92769-7e2f030540a4d622.elb.us-east-1.amazonaws.com:7222
      - name: "nats-west"
        urls:
          - nats://natsgate:NATSC!u5t3rGa73way@57.154.178.93:7222
  merge:
    accounts:
      SYS:
        users:
          - user: sys
            pass: sysuser
      teamA:
        default_permissions:
          publish:
            allow: "math.numbers.>"
          subscribe:
            allow: 
            - "math.numbers.>"
            - "_INBOX.>" # necessary for responses
          allow_responses: true
        jetstream: enabled
        users:
          - user: natseast
            pass: NATSC!u5t3r3@st
          - user: natswest
            pass: NATSC!u5t3rW3st
      teamB:
        users:
          - user: natsUserB
            pass: NATS_U$3R_b33
    system_account: SYS

podTemplate:
  topologySpreadConstraints:
    kubernetes.io/hostname:
      maxSkew: 1
      whenUnsatisfiable: DoNotSchedule

service:
  ports:
    gateway:
      enabled: true
  merge:
    metadata:
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-type: external
        service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
        service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    spec:
      type: LoadBalancer
      publishNotReadyAddresses: true
      ports:
        - name: nats
          port: 4222
          targetPort: 4222
        - name: gateway
          port: 7222
          targetPort: 7222


