config:
  cluster:
    enabled: true
    replicas: 3
  jetstream:
    enabled: true
    fileStore:
      pvc:
        size: 10Gi
  leafnodes:
    enabled: true
  gateway:
    enabled: true
    merge:
      advertise: "k8s-default-natseks-1fbb70eb26-85458df31024e600.elb.us-east-1.amazonaws.com"
      authorization:
        user: natsgate
        password: NATSC!u5t3rG@73w@y
      gateways: 
      - name: "nats-eks"
        urls:
          - nats://natsgate:NATSC!u5t3rG@73w@y@k8s-default-natseks-1fbb70eb26-85458df31024e600.elb.us-east-1.amazonaws.com:7222
      - name: "nats-azure"
        urls:
          - nats://natsgate:NATSC!u5t3rG@73w@y@13.91.37.138:7222
  merge:
    accounts:
      SYS:
        users:
          - user: sys
            pass: sysuser
      global:
        jetstream: enabled
        users:
          - user: natsedge
            pass: NATSeDg3Us3r!
          - user: natseast
            pass: NATSC!u5t3r3@st
          - user: natswest
            pass: NATSC!u5t3rW3st
    system_account: SYS

podTemplate:
  topologySpreadConstraints:
    kubernetes.io/hostname:
      maxSkew: 1
      whenUnsatisfiable: DoNotSchedule
  merge:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "7777"
        prometheus.io/scrape_port: "7777"
    spec:
      containers:
      - name: nats
        image: nats:2.10.26-alpine
        args:
          - '--config'
          - /etc/nats-config/nats.conf
        ports:
          - name: nats
            containerPort: 4222
            protocol: TCP
          - name: leafnodes
            containerPort: 7422
            protocol: TCP
          - name: cluster
            containerPort: 6222
            protocol: TCP
          - name: monitor
            containerPort: 8222
            protocol: TCP
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.name
          - name: SERVER_NAME
            value: $(POD_NAME)
        resources: {}
        volumeMounts:
          - name: config
            mountPath: /etc/nats-config
          - name: pid
            mountPath: /var/run/nats
          - name: nats-eks-js
            mountPath: /data
        livenessProbe:
          httpGet:
            path: /healthz?js-enabled-only=true
            port: monitor
            scheme: HTTP
          initialDelaySeconds: 10
          timeoutSeconds: 5
          periodSeconds: 30
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /healthz?js-server-only=true
            port: monitor
            scheme: HTTP
          initialDelaySeconds: 10
          timeoutSeconds: 5
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /healthz
            port: monitor
            scheme: HTTP
          initialDelaySeconds: 10
          timeoutSeconds: 5
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 90
        lifecycle:
          preStop:
            exec:
              command:
                - nats-server
                - '-sl=ldm=/var/run/nats/nats.pid'
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        imagePullPolicy: IfNotPresent
      - name: reloader
        image: natsio/nats-server-config-reloader:0.16.1
        args:
          - '-pid'
          - /var/run/nats/nats.pid
          - '-config'
          - /etc/nats-config/nats.conf
        resources: {}
        volumeMounts:
          - name: pid
            mountPath: /var/run/nats
          - name: config
            mountPath: /etc/nats-config
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        imagePullPolicy: IfNotPresent
      - name: prometheus-nats-exporter
        image: natsio/prometheus-nats-exporter:0.16.0
        args:
          - '-port'
          - '7777'
          - '-varz'
          - '-accstatz'
          - '-channelz'
          - '-connz'
          - '-connz_detailed'
          - '-routez'
          - '-serverz'
          - '-subz'
          - '-gatewayz'
          - '-jsz=all'
          - '-leafz'
          - http://localhost:8222
        ports:
          - name: http
            containerPort: 7777
            protocol: TCP

service:
  ports:
    gateway:
      enabled: true
  merge:
    metadata:
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-type: external
        service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
        service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    spec:
      type: LoadBalancer
      publishNotReadyAddresses: true
      ports:
        - name: nats
          port: 4222
          targetPort: 4222
        - name: gateway
          port: 7222
          targetPort: 7222
        - name: monitor
          port: 8222
          targetPort: 8222
        - name: leafnodes
          port: 7422
          targetPort: 7422

