config:
  cluster:
    enabled: true
    replicas: 3
  jetstream:
    enabled: true
    fileStore:
      pvc:
        size: 10Gi
  leafnodes:
    enabled: true
  gateway:
    enabled: true
    merge:
      # advertise: "k8s-default-natseks-1fbb70eb26-85458df31024e600.elb.us-east-1.amazonaws.com"
      authorization:
        user: natsgate
        password: NATSC!u5t3rG@73w@y
      gateways: []
      # - name: "nats-eks"
      #   urls:
      #     - nats://natsgate:NATSC!u5t3rG@73w@y@k8s-default-natseks-1fbb70eb26-85458df31024e600.elb.us-east-1.amazonaws.com:7222
      # - name: "nats-azure"
      #   urls:
      #     - nats://natsgate:NATSC!u5t3rG@73w@y@13.91.37.138:7222
  merge:
    accounts:
      SYS:
        users:
          - user: sys
            pass: sysuser
      global:
        jetstream: enabled
        users:
          - user: natsedge
            pass: NATSeDg3Us3r!
          - user: natseast
            pass: NATSC!u5t3r3@st
          - user: natswest
            pass: NATSC!u5t3rW3st
    system_account: SYS

podTemplate:
  topologySpreadConstraints:
    kubernetes.io/hostname:
      maxSkew: 1
      whenUnsatisfiable: DoNotSchedule

service:
  ports:
    gateway:
      enabled: true
  merge:
    metadata:
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-type: external
        service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
        service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    spec:
      type: LoadBalancer
      publishNotReadyAddresses: true
      ports:
        - name: nats
          port: 4222
          targetPort: 4222
        - name: gateway
          port: 7222
          targetPort: 7222


