apiVersion: v1
kind: Secret
metadata:
  name: nats-credentials
  labels:
    app: nats
type: Opaque
data:
  operator-username: bmF0c19vcGVyYXRvcnM=  # Base64 encoded value of "nats_operators"
  operator-password: TkFUUzBwZXJAdG9ycw==  # Base64 encoded value of "NATS0per@tors"
  requester-username: bmF0c19yZXF1ZXN0ZXJz  # Base64 encoded value of "nats_requesters"
  requester-password: TkFUU1IzcXUzc3QzcnM=  # Base64 encoded value of "NATSR3qu3st3rs"
  region: V2VzdA== # Base64 encoded value of "West"
  nats-servers: bmF0czovL25hdHMtd2VzdC5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsOjQyMjI= # Base64 encoded value of "nats://nats-west.default.svc.cluster.local:4222"