apiVersion: apps/v1
kind: Deployment
metadata:
  name: adder-deployment
  labels:
    app: adder
spec:
  replicas: 3
  selector:
    matchLabels:
      app: adder
  template:
    metadata:
      labels:
        app: adder
    spec:
      containers:
        - name: adder
          image: ghcr.io/colinjlacy/colinjlacy/nats-cluster-demo-adder:latest
          env:
            - name: NATS_USERNAME
              valueFrom:
                secretKeyRef:
                  name: nats-credentials
                  key: username
            - name: NATS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nats-credentials
                  key: password
            - name: NATS_URLS
              valueFrom:
                configMapKeyRef:
                  name: service-config
                  key: nats-urls
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
            requests:
              memory: "128Mi"
              cpu: "250m"