apiVersion: apps/v1
kind: Deployment
metadata:
  name: divider-deployment
  labels:
    app: divider
spec:
  replicas: 3
  selector:
    matchLabels:
      app: divider
  template:
    metadata:
      labels:
        app: divider
    spec:
      containers:
        - name: divider
          image: ghcr.io/colinjlacy/colinjlacy/nats-cluster-demo-divider:latest
          imagePullPolicy: Always
          env:
            - name: NATS_USER
              valueFrom:
                secretKeyRef:
                  name: nats-credentials
                  key: username
            - name: NATS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nats-credentials
                  key: password
            - name: NATS_SERVERS
              valueFrom:
                secretKeyRef:
                  name: nats-credentials
                  key: nats-servers
            - name: NATS_REGION 
              valueFrom:
                secretKeyRef:
                  name: nats-credentials
                  key: region
          resources:
            limits:
              memory: "128Mi"
              cpu: "250m"
            requests:
              memory: "128Mi"
              cpu: "250m"