apiVersion: v1
kind: ConfigMap
metadata:
  name: service-config
  labels:
    app: service
data:
  nats-urls: "nats://nats-kind-0.nats-kind-headless:4222,nats://nats-kind-1.nats-kind-headless:4222,nats://nats-kind-2.nats-kind-headless:4222"