---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nats-admin
  labels:
    userType: bot
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nats-admin-cluster-admin-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: nats-admin
  namespace: default
---
apiVersion: v1
kind: Secret
metadata:
  name: nats-admin-token
  annotations:
    kubernetes.io/service-account.name: nats-admin
type: kubernetes.io/service-account-token
