name: Build and Push Docker Images

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Log in to GitHub Docker Registry
      - name: Log in to GitHub Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Loop through each folder in /services and build/push Docker images
      - name: Build and push Docker images
        run: |
          for service in services/*; do
            if [ -d "$service" ] && [ -f "$service/Dockerfile" ]; then
              # Extract the service name from the folder name
              service_name=$(basename "$service")

              # Build the Docker image
              docker build -t ghcr.io/${{ github.repository_owner }}/${{ github.repository }}-$service_name:latest $service

              # Push the Docker image to GitHub Packages
              docker push ghcr.io/${{ github.repository_owner }}/${{ github.repository }}-$service_name:latest
            fi
          done